### ISSUE TITLE
Cannot start container. docker can't find "/usr/lib/rstudio-server/bin/server"

### ISSUE THREAD

**Issue by fccoelho** [dceoy/rstudio-server-docker#4]
I am getting the following error when starting with docker-compose:

```
Cannot start service rstudio-server: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/lib/rstudio-server/bin/server\": stat /usr/lib/rstudio-server/bin/server: no such file or directory": unknown
```

here is my Dockerfile

```
FROM dceoy/rstudio-server

USER root
RUN apt-get update && apt-get -y install \
    apt-utils \
    tzdata \
    libudunits2-dev \
    libsodium-dev \
    graphviz \
    dirmngr \
    gpg-agent \
    vim \
    gawk \
    less \
    libcurl4-openssl-dev \
    libjpeg-turbo8-dev \
    gdal-bin \
    proj-bin \
    lbzip2 \
    libfftw3-dev \
    libgeos-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libhdf4-alt-dev \
    libhdf5-dev \
    libjq-dev \
#     liblwgeom-dev \
    libpq-dev \
    libproj-dev \
    libprotobuf-dev \
    libnetcdf-dev \
    libsqlite3-dev \
    netcdf-bin \
    protobuf-compiler \
    sqlite3 \
    tk-dev \
    unixodbc-dev \
    software-properties-common \
    cron 


# install the R dependencies
COPY install.R /tmp/
RUN R -f /tmp/install.R
```
my docker-compose.yml:
```yaml
version: "3"
services: 
  rstudio-server:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - /rstudio-server-data:/home/rstudio
    working_dir:
      /home/rstudio
    entrypoint:
      - /usr/lib/rstudio-server/bin/server
    command:
      - --server-daemonize=0
      - --server-app-armor-enabled=0

volumes:
  rstudio-server-data: 

```
